---
- name: Deploy dalu-to-telegram to DC
  hosts: dc
  gather_facts: no
  tasks:
    - name: 1. Fetch and Reset Git Repository
      command: su -c 'chroot /data/local/debian /bin/bash -c "export PATH=/usr/local/bin:/usr/bin:/bin && cd /root/dalu-to-telegram && git fetch origin && git reset --hard origin/main"'
      register: git_out

    - name: Show Git Output
      debug:
        var: git_out.stdout_lines

    - name: 2. Build Source (and Install dependencies if needed)
      command: su -c 'chroot /data/local/debian /bin/bash -c "export PATH=/usr/local/bin:/usr/bin:/bin && cd /root/dalu-to-telegram && CI=true npx pnpm run build"'
      register: build_out

    - name: Show Build Output
      debug:
        var: build_out.stdout_lines

    - name: 3. Restart Service
      command: su -c 'chroot /data/local/debian /bin/bash -c "export PATH=/usr/local/bin:/usr/bin:/bin && /usr/bin/sv restart zalo-tg"'
      register: restart_out

    - name: Show Restart Output
      debug:
        var: restart_out.stdout_lines
